services:
  postgres:
    container_name: postgres
    image: postgres:16-bookworm
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - courses:/var/lib/postgresql/data
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_DB: access
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0
    restart: always
    privileged: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./access/theme:/opt/keycloak/themes/access/login
      - ./access/realm.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm
    depends_on:
      - postgres
    environment:
      KC_FEATURES: preview,docker
      KC_DB: postgres
      KC_DB_URL: ${POSTGRES_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      CLIENT_SECRET: ${CLIENT_SECRET}

volumes:
  courses:
