version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: access
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./theme:/opt/keycloak/themes/access/login
    command: start-dev
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/access
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

volumes:
  postgres_data:
    driver: local